Feature/jan/ver mascotas
Janescobar92/PETBUDDY-BACKEND pull request #5
Opened 2020-11-25 17:15 UTC by Janescobar92

@JimenaEB 
@JuanLGC 
@jc-alcaldev 
@LorellaRM

2020-11-26 16:01 UTC, JimenaEB requested changes

2020-11-26 16:01 UTC, JimenaEB commented on src/main.py
> +        print("entro en except")
Borra los prints

2020-11-26 16:01 UTC, JimenaEB commented on src/models.py
> +    def read_pets(cls, id_user):
Es mejor nombre read_pets_by_user

2020-11-26 16:04 UTC, JimenaEB commented on src/main.py
> +def read_user_pets(id_user):
Lo mismo, mejor read_pets_by_user

2020-12-01 16:26 UTC, Janescobar92 commented on src/main.py
> +        print("entro en except")
borrado

2020-12-01 16:28 UTC, Janescobar92 commented on src/models.py
> +    def read_pets(cls, id_user):
corregido

2020-12-01 16:31 UTC, Janescobar92 commented on src/models.py
> +    def read_pets(cls, id_user):
corregido

2020-12-01 16:32 UTC, Janescobar92 commented on src/main.py
> +def read_user_pets(id_user):
corregido

2020-12-09 17:14 UTC, closed without merging